# Generated by Django 4.2 on 2024-04-29 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, verbose_name='phone_number')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other'), ('Academy', 'Academy')], max_length=10, verbose_name='Type your number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phonr', to=settings.AUTH_USER_MODEL, verbose_name='user_phonr')),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('githup', models.URLField(verbose_name='githup')),
                ('x', models.URLField(verbose_name='x')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
                ('emil', models.EmailField(max_length=254, verbose_name='emil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Social_media_user', to=settings.AUTH_USER_MODEL, verbose_name='Social_media_user')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/', verbose_name='user image')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('address', models.CharField(max_length=50, verbose_name='adress')),
                ('dateofbirthday', models.DateField(verbose_name='Date_of_Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user_profile')),
            ],
        ),
    ]
