# Generated by Django 4.2 on 2024-05-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userphonenumber_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateofbirthday',
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Academy', 'Academy'), ('Office', 'Office'), ('Other', 'Other')], max_length=10, verbose_name='Type your number'),
        ),
    ]
