# Generated by Django 4.2 on 2024-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userphonenumber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other'), ('Academy', 'Academy')], max_length=10, verbose_name='Type your number'),
        ),
    ]
