# Generated by Django 4.2 on 2024-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userphonenumber_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphonenumber',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='emil',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='emil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='githup',
            field=models.URLField(blank=True, null=True, verbose_name='githup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='x',
            field=models.URLField(blank=True, null=True, verbose_name='x'),
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
        migrations.DeleteModel(
            name='UserPhoneNumber',
        ),
    ]
