# Generated by Django 4.2 on 2024-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
