# Generated by Django 4.2 on 2024-04-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=60, verbose_name='doctor_name')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('subtitel', models.CharField(max_length=300, verbose_name='about')),
                ('vediourl', models.URLField(blank=True, null=True)),
                ('urlcourses', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodmapimage', models.ImageField(upload_to='rodmap_image', verbose_name='rodmapimage')),
                ('is_paid', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='courses_image', verbose_name='image')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_content', verbose_name='doctor_name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.section', verbose_name='section')),
            ],
        ),
    ]
