# Generated by Django 4.2 on 2024-05-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_content_image_course_content_subtitell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='subtitell',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='doc'),
        ),
    ]
