# Generated by Django 4.2 on 2024-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_content_subtitell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='subtitel',
            field=models.TextField(max_length=300, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='subtitell',
            field=models.CharField(max_length=300, null=True, verbose_name='doc'),
        ),
    ]
