# Generated by Django 4.2 on 2024-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_content_subtitel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='subtitel',
            field=models.TextField(max_length=300, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='subtitell',
            field=models.TextField(default=3, max_length=300, verbose_name='doc'),
            preserve_default=False,
        ),
    ]
