# Generated by Django 4.2 on 2024-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_content_subtitel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='image',
            field=models.ImageField(default=1, upload_to='doctor_image', verbose_name='userimage'),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='subtitel',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='subtitell',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='doc'),
        ),
    ]
