# Generated by Django 4.2 on 2024-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_content_urlcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='image',
            field=models.ImageField(default='midia/doc.jpeg', upload_to='doctor_image', verbose_name='userimage'),
        ),
    ]
